# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8bcf214d55b614175732abb7f563ff96f8373af71f9d8c172aeee24c837c10607974437e88e3a14fe1d6f12782c192974ab8672bc3f5e0fe9b3a08a85554fc3

test:
  secret_key_base: d8755d732cd14dedc9bfaf795e9c570dc8ea5c2970d3506253edc72805baf296b4b9e94aeecf8adcb7f7c101274e5b35144d9069a484e16dc6de74ff4b8e01c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
