# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 915da0baf6f2727e31eb9b4e6679056fdff142fa2b10f70f1f6d1e2a1cd38a594926cf711f29605b69819fce5533b0679fe892cccc0b579d16aaf9563f66f2ab

test:
  secret_key_base: 45b386eb231945362b87f42696f408e13ccb4280557d7474b76c2077c182a5baf5b2910f416bc905191281e60bdd170822dc5f8006bbc02d9c736f94e48c870b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
